### ISSUE TITLE
Broken proportions of the image

### ISSUE THREAD

**Issue by abdula** [html5cat/redactor-js#21]
By increasing the picture when one side of the picture reaches the boundary of the editor, the second continues to increase, resulting in the broken proportion.

**Comment by html5cat** [comment]
@abdula thanks for your feedback! This is not the official redactor-js website, however the issues here get read by the development team. If you have a support request feel free to forward it here http://redactorjs.com/

**Comment by opes** [comment]
@abdula I fixed this problem by adding a second condition to the following line and adding an additional variable:

In the `resizeImage` method, add the following variable right at the beginning of the method:

``` javascript
var $el = this.$el;
```

Then in that same method, just down below, add a width testing condition to the following line:

``` javascript
if (new_h > min_h)
```

Change to:

``` javascript
if (new_h > min_h && new_w < $el.width())
```

Note that if you have a specified height on the redactor editor element, the image will be resizable beyond the boundaries of the height of the editor and this fix may not work.  I'll see if I can tweak it a bit more and fix it.

**Comment by abdula** [comment]
Thanks for help, but seems resizing images  still not work correct. In
options of redactor i set autoresize:true;

http://awesomescreenshot.com/0b5i319ef - base image
http://awesomescreenshot.com/056i31g80 - apply resize
http://awesomescreenshot.com/0cai31m91 - apply resize

2012/10/4 opes notifications@github.com

**Comment by opes** [comment]
@abdula I updated my comment.  Undo the height portion and try the above.  I can't get it to work if the editable content has a specified height on it, but it works if you have just the width specified.
