### ISSUE TITLE
air mode broken

### ISSUE THREAD

**Issue by daslicht** [html5cat/redactor-js#78]
Hello,
 as far as i set air:true I get :
Uncaught TypeError: Cannot call method 'apply' of undefined create-post:1

Any idea ? Is Air mode should be available in 8.2.2 no ?
~Marc

**Comment by tchapi** [comment]
Long shot, but this is corrected in https://github.com/tchapi/redactor-js and https://github.com/joashxu/redactor-js

**Comment by born2discover** [comment]
@tchapi Tried to downloading source from both links but doesn't seem to resolve the issue I am afraid.

Still got:
    Uncaught TypeError: Cannot read property 'apply' of undefined

Using Jquery 2.1.1 from Google CDN.

**Comment by tchapi** [comment]
See http://jsfiddle.net/AVFxh/3/ where it works. I just copied and paste the raw JS and CSS files from my master : https://github.com/tchapi/redactor-js/tree/master/redactor and added : 

``` javascript
$(document).ready(function(){
    $("#stuff").redactor({air: true});
});
```

You might have an issue somewhere else in your code. Happy to help if you provide me with a jsfiddle for your own implementation
